#: kivy 1.9
#: import ScreenManager kivy.uix.screenmanager.ScreenManager
#: import Screen kivy.uix.screenmanager.ScreenManager
#: import MenuScreen screen
#: import SettingsScreen screen
<CustLabel@Label>:
    color: .761, .190, .810, 1
ScreenManager:
    id: screen_manager
    MenuScreen:
        id: menu_screen
        name: 'MenuScreen'
        manager: 'screen_manager'
    SettingsScreen:
        id: settings_screen
        name: 'SettingsScreen'
        manager: 'screen_manager'

<MenuScreen>:
    BoxLayout:
        canvas:
            Color:
                rgb: 1, 1, 1
            Rectangle:
                size: root.size
        orientation: 'vertical'
        KivyCamera:
            id: qrcam
            resolution: (640, 480)
        Button:
            id: butt_start
            text: "start"
            size_hint_y: None
            height: '48dp'
            on_press: root.dostart()
        Button:
            id: butt_exit
            text: "stop"
            size_hint_y: None
            height: '48dp'
            on_press: root.doexit()
        Button:
            text: 'Settings'
            size_hint_y: None
            height: '48dp'
            on_press: app.root.current = 'SettingsScreen'
        Button:
            text: 'Exit'
            size_hint_y: None
            height: '48dp'
            on_press: root.closeApp()


<SettingsScreen>:
    orientation: "vertical"
    padding: 10
    spacing: 10

    BoxLayout:
        orientation: "vertical"
        height: 20
        CustLabel:
            text: "Option1"
            size_hint_x: .40
            font_size:16
        CheckBox:
            color:.294, .761, .623
            on_active: root.checkbox_click1(self, self.active)
            size_hint_x: .40
        CustLabel:
            text: "Option2"
            size_hint_x: .40
            font_size:16
        CheckBox:
            color:.294, .761, .623
            on_active: root.checkbox_click2(self, self.active)
            size_hint_x: .40
        CustLabel:
            text: "Option3"
            size_hint_x: .40
            font_size:16
        CheckBox:
            color:.294, .761, .623
            on_active: root.checkbox_click3(self, self.active)
            size_hint_x: .40




        Button:
            text: 'Back to menu'
            size_hint_y: None
            height: '48dp'
            on_press: app.root.current = 'MenuScreen'